### ISSUE TITLE
How To Put Multiple Auto Displayed Promo Images with a Single Sprite?

### ISSUE THREAD

**Issue by hammouda101010** [Community-Spotlight/promotion-media#2]
@SharkPool-SP disscussion/suggestion

**Comment by SharkPool-SP** [comment]
You dont. You should be using Manual Display instead

**Comment by hammouda101010** [comment]
How to Use Manual Display?

**Comment by SharkPool-SP** [comment]
> How to Use Manual Display?

If its a image, you can use the skins extension to display the promo, if its a video, use the video extension. Then to redirect to the promoter site, use the network and json extension

**Comment by hammouda101010** [comment]
ok can you make a tutorial written in a document or as a video?

**Comment by SharkPool-SP** [comment]
theres documentation for those extensions, putting it together is self explanatory

**Comment by hammouda101010** [comment]
i meant make a guide how to setup a Manual Display

**Comment by SharkPool-SP** [comment]
> i meant make a guide how to setup a Manual Display

use the manual display blocks, it returns a JSON with all the promotion information

The ones you should focus on is the "url" (link to the promotion media) and "promoter-url" (link to the promoters site)
